### ISSUE TITLE
Docs の TODO

### ISSUE THREAD

**Issue by tsutaj** [kmyk/online-judge-verify-helper#28]
やることがいろいろあるのでとりあえずまとめを書く (Milestone 自体に何かしらコメントを入れる機能がほしいけど存在しなさそうだった・・・)

## TODO List

- [x] 型ヒントのサポートライブラリ [typing](https://docs.python.org/ja/3/library/typing.html) (>= 3.5) を使って、型を明記
- [x] パス周りを [pathlib](https://docs.python.org/ja/3/library/pathlib.html) (>= 3.4) を使って書き直す
- [x] `cpp` ファイルが別の `cpp` ファイルに依存する場合に対応できていないらしい (参考: https://github.com/kmyk/online-judge-verify-helper/issues/2#issuecomment-562052866)
- [x] docs ビルド時の config は `json` か何かから情報を取ってくるようにする
- [x] docs の html から、それに対応するGitHub 上のリポジトリ (のソースコードのページとか) に飛ぶボタンを付ける
- [x] 波括弧が kramdown の liquid として認識されてしまう問題の修正

## メモ

* [GitHub Metadata](https://jekyll.github.io/github-metadata/site.github/): GitHub Pages で利用できる変数の一覧っぽい

**Comment by tsutaj** [comment]
パスと依存関係をまずやる

**Comment by tsutaj** [comment]
とりあえず型ヒントと os.path -> pathlib の作業は終わりました

**Comment by tsutaj** [comment]
このリポジトリの CI で落ちてますね (pylint などでチェックしてるのを今知りました・・・)
なおします

**Comment by tsutaj** [comment]
veriffy のビルドは通りました
```
docs.py:631: error: Unsupported operand types for / ("Path" and "object")
docs.py:634: error: No overload variant of "write" of "BinaryIO" matches argument types [builtins.object*]
```

format のビルドなのですが、なぜ落ちるのかがわからないです・・・。たしか @kmyk さんが書いてくれたところで、`asset` は Dict 型であって `path' キーには `pathlib.Path` 型、`data` にはコンテンツが入っているので整合性は取れていると思うのですが

**Comment by tsutaj** [comment]
このエラーがあるせいで色々なところでビルドが行われていなくてつらいので、最悪なんですが該当箇所だけ `ignore` して一旦やり過ごしました・・・ (あとで直したいです)
今までビルドがうまくいっていなかった自分のページ https://tsutaj.github.io/cpp_library/ も今度は反映されるようになりました

**Comment by tsutaj** [comment]
デフォルトのテーマを Dinky にしました
若干ズルなんですが、このテーマで GitHub Pages を利用すると「View on GitHub」ボタンが勝手につくので、docs の html から、それに対応するGitHub 上のリポジトリに飛ぶボタンを付けるのは半分解決したことにします。各ファイルからそれに対応する GitHub 上のファイルにも飛べるほうが嬉しいと思うので、それはこれから付け足します

**Comment by beet-aizu** [comment]
テーマをカスタマイズできるとうれしさがありそう（設定ファイルに書くとか）

**Comment by tsutaj** [comment]
いまから Config 周りをやろうと思うんですが、そこで `theme: ほげほげ` と指定できるようにしますね

**Comment by tsutaj** [comment]
> docs の html から、それに対応するGitHub 上のリポジトリ (のソースコードのページとか) に飛ぶボタンを付ける

これを解決した :tada:

* トップページに CI のビルドステータスと last commit date を表示

![Screenshot at 2019-12-10 12-11-20](https://user-images.githubusercontent.com/19629946/70492008-4eaf6680-1b46-11ea-95b6-59d2d499b972.png)

* 各ファイルページに GitHub へのリンクと last commit date を表示

![Screenshot at 2019-12-10 12-11-34](https://user-images.githubusercontent.com/19629946/70492011-52db8400-1b46-11ea-874f-ae2ac9f1a902.png)

**Comment by kmyk** [comment]
どんどんおしゃれになっていっててすごい

**Comment by tsutaj** [comment]
> テーマをカスタマイズできるとうれしさがありそう（設定ファイルに書くとか）

これも解決しました
ライブラリが存在するリポジトリのうち、`oj-verify docs` を実行するのと同じ階層に `_docs.yml` を設置すると、その設定が反映された docs を作ります

例えば以下のように書きます (参考: https://github.com/kmyk/online-judge-verify-helper/blob/master/_docs.yml)

```yml
# title (default: 'C++ Competitive Programming Library')
title: 'Docs by "online-judge-verify-helper"'
# description (default: '')
description: 'This documentation is generated automatically.'

# jekyll theme (default: 'jekyll-theme-dinky')
theme: 'jekyll-theme-dinky'

# show table-of-contents (default: False)
toc: True

# generate HTML as well as Markdown (default: False)
html: False

# show library files with categorizing (default: True)
categorize_library: True
# show verify files with categorizing (default: False)
categorize_verify: False

```

**Comment by kmyk** [comment]
そろそろ一度 version を更新してもよさそう

**Comment by tsutaj** [comment]
`data/assets/_config.yml` と `.verify-helper/docs/_config.yml` で分業する意味はないため、後者のほうにまとめました
`title` や `description` など、Docs 特有の setting にしたいものたちは本家 Jekyll の setting と衝突しがちなので、以下の形で書くことにしました

```yml
# jekyll theme (default: 'jekyll-theme-dinky')
theme: 'jekyll-theme-dinky'

docs:
  # title (default: 'C++ Competitive Programming Library')
  title: 'Docs by "online-judge-verify-helper"'
  # description (default: '')
  description: 'This documentation is generated automatically.'

  # show table-of-contents (default: False)
  toc: True

  # generate HTML as well as Markdown (default: False)
  html: False

  # show library files with categorizing (default: True)
  categorize_library: True
  # show verify files with categorizing (default: False)
  categorize_verify: False

# plugin (necessary for showing emoji)
plugins:
  - jemoji
```

feature 増えてきたのでバージョン上げますね

**Comment by tsutaj** [comment]
依存関係を再帰的に見ておらず、2 つ以上ディレクトリが離れていると表示されていなかったので直しました (shell script から `list-dependencies` をもってきた)

**Comment by kmyk** [comment]
@tsutaj バージョン上げたりしたらついでに Twitter で宣伝しておいてください。必須ではないです。せっかくよい機能を実装してくれてるのに、何も言わないと誰も気付かないためです
たぶんこの thread の一番下に追加するのが最適です https://twitter.com/a3VtYQo/status/1199132099820703746

**Comment by beet-aizu** [comment]
#29 を処理して timestamp.json に保存するようにしました（timestampの下のmd5で生成するやつを更新する処理は結局書いてません（は？）書いた方がよければ書きます）
